### ISSUE TITLE
Gpodder 4.8.0: new text to translate

### ISSUE THREAD

**Issue by carmenfdezb** [gpodder/gpodder-sailfish#101]
Hi @mibuthu, @sfbg and @fravaccaro!!
Gpodder v4.8.0 will be released very soon and new strings have been added to translate, in case you want to translate it, please do PR.
Thank you for your work!

**Comment by Keeper-of-the-Keys** [comment]
Thanks everyone, I think all translations were done, I'm preparing the release for tonight/tomorrow.

**Comment by mibuthu** [comment]
Sorry I'm a bit late, but I have committed the german translation now (#105).
