### ISSUE TITLE
Show Wait/Load message at app startup

### ISSUE THREAD

**Issue by Pohli** [gpodder/gpodder-sailfish#112]
When I start gPodder on my Jolla Phone it takes up to a few seconds until subscriptions are displayed. Until that the app shows first a spinning wheel and then the message "No subscriptions". This is a bit irritating. Either the spinning wheel should be displayed until the subscriptions are really shown or there should be a Loading message or similar instead of "No subscriptions" message.

Jolla Phone with SFOS 3.0.1.11 and gPodder 4.9.0

**Comment by Keeper-of-the-Keys** [comment]
Thanks for reporting, we'll see if we can fix that.
