### ISSUE TITLE
[Feature Request] Podcast name or cover art to filtering list?

### ISSUE THREAD

**Issue by Zastin** [gpodder/gpodder-sailfish#113]
Hi,

I have lots of podcast in gpodder. When I use filtering, it show me episode name. It is hard to know witch podcast that episode belong and I have to make extra work to check it. If it is possible make some indicator example cover art picture before episode name, it will make gpodder use easier.

**Comment by Keeper-of-the-Keys** [comment]
I actually have been thinking about adding some type of search functionality :) we'll see if and how to do this.

**Comment by sfbg** [comment]
@Zastin I am all for the logo (coverart) of the podcast in front of each episode in the filtered list? 

I have the same issue as you, and this solution would solve it for me. I was planning on implementing it, but currently just do not have the time to do it.

**Comment by Keeper-of-the-Keys** [comment]
Hey I'm working on per-episode artwork, I think after I'm done with that it will also resolve this issue.

Hopefully it will be in the upcoming release unless it takes me too long :)

**Comment by Keeper-of-the-Keys** [comment]
Released in 4.11.0
