### ISSUE TITLE
[feature request] Configure downloads location

### ISSUE THREAD

**Issue by ichthyosaurus** [gpodder/gpodder-sailfish#136]
It would be great if there were an option to set a custom download directory. I have several gigabytes of downloaded podcasts and would like to store them on my SD card instead of the small home partition.

**Comment by Keeper-of-the-Keys** [comment]
I am thinking about implementing some more general/per podcast settings hopefully we can add this.

In the mean time another way to do this would be to move the directory to the sd card and create a symlink.
HTH!

**Comment by ichthyosaurus** [comment]
> I am thinking about implementing some more general/per podcast settings hopefully we can add this.

That would be great :)

> In the mean time another way to do this would be to move the directory to the sd card and create a symlink.

Thanks. I already tried that and there were some issues (I don't quite remember) but I'll try again!
