### ISSUE TITLE
Gpodder not working with 3.4.0.22

### ISSUE THREAD

**Issue by peperjohnny** [gpodder/gpodder-sailfish#143]
Hey the new update is there for early adopters, but unfortunately it borks gpodder. The subscriptions do not load. You're not able to add new podcasts. You can't discover Podcasts. I haven't tried import. Maybe this log helps you.

https://pastebin.com/x5YDibvY

I started gpodder and tried to add a new podcast.

**Comment by carmenfdezb** [comment]
You must install python3-sqlite:
`devel-su pkcon install python3-sqlite`

**Comment by peperjohnny** [comment]
You're right that did it. I wonder why it was missing in the first place. But good enoug for me.

**Comment by Keeper-of-the-Keys** [comment]
I think we need to add a dependency to the package so that this happens automatically.

**Comment by Keeper-of-the-Keys** [comment]
Although it seems the lack of sqlite3 is actually breaking SFOS stuff too, so OTOH it belongs in the OS no matter what OTOH if we depend on it ti should be stated

**Comment by carmenfdezb** [comment]
> You're right that did it. Thank you! I wonder why it was missing in the first place. But good enoug for me.

I had the same issue before updating SailfishOS, but I know python3-sqlite was installed

**Comment by Keeper-of-the-Keys** [comment]
I made an emergency release on OpenRepos it already includes the merged changes by @thigg 
Sadly harbour does not allow python3-sqlite as a dependency and the attitude I'm getting from vigo at Jolla makes me want to pull gPodder from the store entirely.

**Comment by thigg** [comment]
@Keeper-of-the-Keys thanks for your efforts. Let me know if I can assist you there somehow.
Isn't it possible to just pack python3-sqlite as a dependency into the rpm instead of requiring it via the package manager?

**Comment by Keeper-of-the-Keys** [comment]
It seems the sqlite used to be part of the python package and is now a separate package.

**Comment by Keeper-of-the-Keys** [comment]
@thigg it may be possible but that violates *nix philosophy and complicates packaging.
As things stand maintaining both an OpenRepos and a harbour version is a nuisance if Jolla doesn't come through on this issue I think we'll do what more and more devs do - move the application to be OpenRepos only.

Vigo from Jolla has posted on the forum topic that he opened an internal bug to add python3-sqlite as an allowed dependency, so right now we wait.

**Comment by thigg** [comment]
Thanks for the insight. Totally agree with you. Packaging the dependency into the rpm just curls my toenails up...
Seeing gPodder removed from the official store would be very sad, but maybe it is needed to increase the pressure on jolla there.

**Comment by Keeper-of-the-Keys** [comment]
Just a small update - python3-sqlite was added as allowed **but** that package doesn't exist on SFOS < 3.4 so now the next challenge is to make a spec file have a conditional dependency, so far I have not been able to find what variables Jolla exposes to the RPM process.

**Comment by thigg** [comment]
maybe this helps? https://blog.jasonantman.com/2012/09/dumping-all-macros-from-an-rpm-spec-file/

**Comment by Keeper-of-the-Keys** [comment]
`rpm --showrc`
Does not seem to show any SFOS version related symbol unless I'm missing something.

**Comment by Keeper-of-the-Keys** [comment]
It seems Jolla has resolved this issue fairly elegantly by making pyotherside (the library that binds between QML and python) depend on python3-sqlite, if someone who did not have 4.11.9 installed (or already manually installed python3-sqlite) we can close this.

**Comment by peperjohnny** [comment]
Since Jolla included python3-sqlite in 3.4.0.24 this can be considered closed.
