### ISSUE TITLE
No feedback if PodcastURL is invalid

### ISSUE THREAD

**Issue by thigg** [gpodder/gpodder-sailfish#152]
1. add a new podcast url which will result in a 404 e.g. https://saodjhsao.podigee.io/feed/mp3
2. click the button

IS: Returning to the PodcastsPage, nothing happens
EXPECTED: Some feedback that the url was invalid. The dialog stays open, user can fix the url and try again.

**Comment by Keeper-of-the-Keys** [comment]
Absolutely something we should work on, most times for me when it fails I have a rotating "trying to add animation" that just never ends.
Has been something on my wishlist for a while, thanks for opening the bug.

**Comment by Keeper-of-the-Keys** [comment]
4.17.0 now gives feeback, lmk if you'd like better/more/different.
