### ISSUE TITLE
SailfishOS 4.0.1.45 (EA) shows no buttons with gpodder 4.11.9

### ISSUE THREAD

**Issue by ummon29** [gpodder/gpodder-sailfish#159]
Hello,

seems like SailfishOS 4.0.1.45 (Early Access) shows no buttons with gpodder 4.11.9. The App starts fine and everything with pulley menus woks, but everywhere where buttons are expected (play, download etc) only an empty backgroundfield is shown and no interaction is possible.

Thanks for your work on this great app.

**Comment by Keeper-of-the-Keys** [comment]
Hey unmon29,
We're looking into it, not yet sure what is causing it.
Thanks!

**Comment by Keeper-of-the-Keys** [comment]
Hey,
I won't be able to do a full fix/release until tomorrow, in the mean time if you want things to work you can modify:
/usr/share/harbour-org.gpodder.sailfish/qml/EpisodeItem.qml

line 68 from IconContextMenu to ContextMenu.

This is based on the work of the guys making podQast, located here:

https://gitlab.com/cy8aer/podqast/-/commit/dda0ed1ffa3da774db6d2eadcb2bceb74e78f233

It will change the look/feel a bit but at least it'll work.

Sorry about the inconvenience!

**Comment by ummon29** [comment]
Hello,

thanks for the quick workaround. It works without a problem.
Take your time to fix it properly.

**Comment by Keeper-of-the-Keys** [comment]
Minor update - this fix breaks the menu function in SFOS 3.x (and presumably all versions prior) so I'm holding off on publishing until I find a better solution or SFOS 4.0 is GA.

**Comment by ummon29** [comment]
Take your time. SFOS 4.0 is still EA and the workaround is easy enough and makes gpodder usable again.
I am just looking if and how the same can be done for the player page, were the icons are gone too.
Simply changing the IconMenuItem entries to MenuItem in the PlayerPage.qml didn't achieve the the simple solution I was hoping for. But the Player page is only a minor inconvenience. Play and pause can be reached otherwise and only the rewind/forwad-jump option isn't reachable for the moment.

Thanks again for your work on this App.

**Comment by Keeper-of-the-Keys** [comment]
Fixed in 4.12.0
