### ISSUE TITLE
[feature request] Add MPRIS support for lock window/media buttons

### ISSUE THREAD

**Issue by paulvt** [gpodder/gpodder-sailfish#162]
Now that BT and headset media buttons go via MPRIS (see [release notes](https://forum.sailfishos.org/t/release-notes-verla-4-2-0/7092#media-22)), it would be awesome if gPodder supports MPRIS!

I noticed that Podqast supports this in OpenRepos only, but I don't know if this still needs to be removed to pass Harbour?

**Comment by Keeper-of-the-Keys** [comment]
I'll try to see if harbour indeed accepts this now, not needing to maintain two different packages would be a huge improvement to my quality of life when I do a release :)

**Comment by paulvt** [comment]
Ok, great. I hope so! Thanks.
I would be immensely useful for the use case where people start talking to you and you don't have to fumble with (getting your phone), unlocking, etc.
