### ISSUE TITLE
download button (sailfish OS 4.5.0.16)

### ISSUE THREAD

**Issue by mipstux** [gpodder/gpodder-sailfish#170]
Hello,
No big issue with the last update of Sailfish OS except the download button that disappear :-(
I can click on the "shadow" download button and it works. Just the icon is not there.
![Icon-button-download_edit](https://user-images.githubusercontent.com/97527160/218145007-437fcc95-931f-4b3a-808d-475fd3cbf007.jpg)

**Comment by Keeper-of-the-Keys** [comment]
Hey thanks!
We already have a patch for this (#169) hopefully we'll have time to push a new version to the stores soon.
