### ISSUE TITLE
Playback speed setting too many number of fractions - just display 2

### ISSUE THREAD

**Issue by andywuest** [gpodder/gpodder-sailfish#182]
Hi,

when changing the playback speed setting via the slider to a different value: e.g. 1.35 then the playback speed
is displayed as 1.350000000023841858 - which makes no sense at all. It is completely sufficient to display 2 fraction
digits, since you can change the speed in steps of 0.05 anyway.

Cheers,
Andreas

**Comment by Keeper-of-the-Keys** [comment]
Next release will have 0.25 increments.
