### ISSUE TITLE
[Missing Feature] gPodder.net login

### ISSUE THREAD

**Issue by NGC935** [gpodder/gpodder-sailfish#20]
Maybe I didn't find it yet, but I used the gpodder.net account to sync my podcasts. Is it planned to add it in the future?

**Comment by clovis86** [comment]
great news ! 
Maybe opml import/export can be a workaround while waiting for this feature :)

**Comment by bionade24** [comment]
@Keeper-of-the-Keys Are you planning to add this feature once?

**Comment by bionade24** [comment]
@Keeper-of-the-Keys Any comment from you on this?

**Comment by Keeper-of-the-Keys** [comment]
Hi sorry about the delay.
I'd be happy to look at patches to add it, as things stand it is not at the top of my list of priorities of features I'm trying to implement.

If this is already partially/fully implemented in gpodder-core then adding a frontend is of course an option.

**Comment by bionade24** [comment]
> Hi sorry about the delay.
> I'd be happy to look at patches to add it, as things stand it is not at the top of my list of priorities of features I'm trying to implement.
> 
> If this is already partially/fully implemented in gpodder-core then adding a frontend is of course an option.

Thx for your clarification. Now I can take a look at it somewhere in the future and make a PR :)

**Comment by Keeper-of-the-Keys** [comment]
Closing since we disabled gpodder.net plugin.
