### ISSUE TITLE
Localization is needed

### ISSUE THREAD

**Issue by lewadedun** [gpodder/gpodder-sailfish#22]

**Comment by frefell** [comment]
How should this be organized? I'm native german and would like to contribute :)

**Comment by dikonov** [comment]
I support this and promise to make a Russian translation, once the code permits it.

**Comment by mibuthu** [comment]
I think this one can be closed now after #931a4959e6af019cccf6fe98f868de7e5c89f01b

**Comment by carmenfdezb** [comment]
Hi @mibuthu! New text is added to translate, if you want to translate it to German.

**Comment by mibuthu** [comment]
@carmenfdezb, thanks for the info, I will add the translations, but in my opinion the actual filter names are a little bit unclear and inconsistent.

Actual names:
- All
- Fresh
- Downloaded
- Unplayed downloads
- Finished downloads
- Hide deleted
- Deleted episodes
- Short downloads (< 10 min)

Proposal:
- All
- Fresh
- Downloaded
- Downloaded & Unplayed
- Downloaded & Finished
- Hide deleted
- Deleted
- Downloaded & Length < 10min

Probably also the order should be changed to to have all the "Downloaded" successively.

What do you think?

**Comment by sfbg** [comment]
To be honest, I think a general overhaul if the filters is needed since they are quite confusing and too many, if you ask me. 
Or obscure, for example "Short downloads (< 10 min)". Or "Deleted".

"Fresh" as a name is super unclear. It actually means "new and not (finished) downloaded).

I think we have to consider which 3-4 ones make most sense ans implement a more elegant UX for them. But this is clearly a longer term goal.

**Comment by sfbg** [comment]
> I support this and promise to make a Russian translation, once the code permits it. The code must include functions that substitute UI strings with their translated versions and a set of localisation files (.ts for Qt or .po for normal Gtk apps). Meanwhile I switch to Podcatcher, which has i18n in place and is free from "insert API keys" nonsence.

@dikonov now it is possible, it would be great if we had Russian soon.

**Comment by carmenfdezb** [comment]
Definitely, 'Fresh' filter option is nothing clear, indeed I've translated it wrong to Spanish language. What word we can use for this option?
I would keep all the filter options at the moment.

**Comment by Keeper-of-the-Keys** [comment]
I must confess that I have never tried using the filters, the only thing that bugs me atm with that is that the only way to get rid of a downloaded episode is to delete it even though I have no interest in deleting it from the list and only want to clear some space.
