### ISSUE TITLE
Drains battery after downloading episodes

### ISSUE THREAD

**Issue by paulvt** [gpodder/gpodder-sailfish#23]
On 1.1.0.39 (Uitukka), I find that gPodder (as process "sailfish-qml") is drawing 20% CPU all the time, thus draining my battery.
This happens quite often after I have downloaded a few episodes (in parallel).

**Comment by mvock** [comment]
I can confirm the battery drainage (haven’t checked the CPU usage, though) on 1.1.1.27 (Vaarainjärvi).

**Comment by Self-Perfection** [comment]
On my device gPodder (as process "sailfish-qml") uses ~70% of CPU during playback. Device becomes definitely warm and battery is drained by ~20% after an hour of podcast playback.

Looks like CPU usage depends on podcast:
* http://zverik.podfm.ru/osmru/rss/rss.xml - Abnormally high CPU usage
* http://www.wired.co.uk/podcast/rss - CPU usage by "sailfish-qml" during playback is about 5%.

**Comment by paulvt** [comment]
@Self-Perfection Ok, but this bug is about using CPU when not doing anything.  Btw, I can confirm it still happens on 1.1.4.29 since I just saw that gPodder drained my battery 50% more than normal.

**Comment by Self-Perfection** [comment]
@paulvt you are right. I've moved my report to #36

**Comment by Nrde** [comment]
This still hapens with Björnträsket (1.1.7.25) even more than before if possible. Meaning before it was kind of limited to user process taking 25% all the time, now it's escalated to a system process as well which takes 50% cpu. So in total 75% after checking for new episodes and download and then leaving gPodder open. I used Sysmon app to see what is happening. It took 6 hours to drain battery from 100% to 5%

**Comment by paulvt** [comment]
I don't have this problem anymore.  Unless anyone else does, I will close this issue.
