### ISSUE TITLE
Impossible to replay finished episodes

### ISSUE THREAD

**Issue by kelvan** [gpodder/gpodder-sailfish#31]
I just tried to hear an old wrint episode again (deleted and downloaded again), but it always tries to use length+14s as start position and stops immediately.
Setting position to 0:00 and use "Play" pulldown also jumps to the end+14s position and stops.

**Comment by Keeper-of-the-Keys** [comment]
The behavior seems to have changed in later versions, if this issue still exists in 4.7.2 please open a new issue.
Thanks for taking the time to submit issues :)
