### ISSUE TITLE
Editable podcast URL

### ISSUE THREAD

**Issue by paulvt** [gpodder/gpodder-sailfish#32]
The podcast URL is currently not editable, only the name.
As a result I had to update the URL of a podcast that moved by manually updating the JSON database (and gunzippen/gzippen).   Please make it editable as well?

**Comment by paulvt** [comment]
It seems I do have all episodes that I had before the modification in duplicate now.  However, this is better than silently ignoring the 404 on the old URL and seeming like there are no podcast episodes coming anymore.

**Comment by Keeper-of-the-Keys** [comment]
Hi @paulvt, first of thanks for the report, second sorry for the way overdue response.
I started work on this last week for a "podcast settings" kind of page.
However the more I grapple with the issue the more I see why this was never implemented in the past.

How should the application behave when the feed URL changes? Should it re-import everything - basically subscribing? Is it possible to detect which episode changed into which when the permalink (which presumably changed with the feed URL) is different? Should the title be overwritten? etc.

@elelay Is this an issue that was dealt with in mainline gPodder?

Is there an example podcast that has 2 diffent feed URLs I can test with?

**Comment by elelay** [comment]
Hi,
it's not possible in gPodder desktop either, for the rteason you described.

**Comment by Keeper-of-the-Keys** [comment]
@elelay Thanks, it's a bummer I've been barking up the wrong trees recently as far as resolving issues :face_with_head_bandage: 

@paulvt I'm closing this issue since as we explained it's not easily solvable given the current state of things.

The only thing I do think we should do (and was mentioned in #152 ) is better feedback when there are errors with stream.
