### ISSUE TITLE
Opus playback

### ISSUE THREAD

**Issue by toerb** [gpodder/gpodder-sailfish#33]
Hello,
I am on version 4.4.0 and opus items wont play.
After clicking the play item in the UI nothing is happening.
Other mp3 items work just fine.

I mentioned this bug trying to play a file from this feed: http://freakshow.fm/feed/opus/

Best regards,
toerb

**Comment by thp** [comment]
Yes, this needs to be supported in the platform middleware, and then should automatically be supported by gPodder:

https://together.jolla.com/question/5556/upgrade-gstreamer-to-support-opus-codec/

**Comment by thp** [comment]
As an unsupported third party workaround, you could try this:

https://openrepos.net/content/sailfishlib/gst-plugins-bad-extra

**Comment by florianjacob** [comment]
I can confirm opus playback via gpodder works flawlessly in SailfishOS 2.0.0.10. :grin:

**Comment by schmittlauch** [comment]
@thp You can close this issue now. opus support is now present in SailfishOS and because of this in gPodder as well

**Comment by florianjacob** [comment]
( @schmittlauch Meegons (and binaergewitter) ftw! :D )

**Comment by thp** [comment]
Closing as per the recent comments.
