### ISSUE TITLE
Download problems 

### ISSUE THREAD

**Issue by NGC935** [gpodder/gpodder-sailfish#35]
I subscribed this podcast:
http://damals-tm-podcast.de/?feed=damalstm-mp3
and the crawling, parsing and everything is fine. But i'm not able to download a file, nothing is happening when I push download. All other podcast feeds and downloads are working. . How should I debug this? Can anyone reproduce this behaviour?

**Comment by thp** [comment]
Fixed in https://github.com/gpodder/gpodder-core/commit/c6b2f869d6bb9d029fff261f8b2d4aabf40aefcc -- will be part of the next release.
