### ISSUE TITLE
Excessive CPU usage during playback of specific podcasts

### ISSUE THREAD

**Issue by Self-Perfection** [gpodder/gpodder-sailfish#36]
For comparison:
- http://zverik.podfm.ru/osmru/rss/rss.xml - Abnormally high CPU usage, "sailfish-qml" uses about 70% of CPU.
- http://www.wired.co.uk/podcast/rss - CPU usage by "sailfish-qml" during playback is about 5%.

I use gPodder 4.4.0 on 1.1.2.16 (Yliaavanlampi)

**Comment by Self-Perfection** [comment]
I can not reproduce with gPodder 4.6.0. I suppose this is fixed.

**Comment by Self-Perfection** [comment]
Still from time to time my phone becomes hot during podcast playback and `sailfish-qml` process consumes lots of CPU time. I could not reliable sslteps to reproduce this.

**Comment by Keeper-of-the-Keys** [comment]
Hey @Self-Perfection I'm going over old bugs, don't know if you're still using gPodder/SFOS (hope you are), if you are and this still happens can you update us? In the mean time I'm closing this.
