### ISSUE TITLE
Timepicker playbackcontrols are missing

### ISSUE THREAD

**Issue by schmittlauch** [gpodder/gpodder-sailfish#38]
The timepicker, used for rewinding or forward winding the playback, is missing on the play page.
![20150525170433](https://cloud.githubusercontent.com/assets/1479555/7848348/48dea8ce-04cb-11e5-9520-46e97ad6027d.jpg)

This bug appears since updating to gPodder 4.6 on SailfishOS 1.1.4.29

**Comment by thp** [comment]
Yes, this is intended. It aligns the UI with the other gPodder ports and does not use the timepicker widget in a way it was not intended to use. Also, ist looked bad on the tablet, layout-wise. The buttons do the same thing as the timepicker.

**Comment by schmittlauch** [comment]
That's sad, I really liked that idea as it was less about tiny buttons than it was about gestures. But the issue with the tablet seems to be a valid point.

**Comment by thp** [comment]
Yeah, we can probably find a better solution down the road that works for both phone and tablet, so assume that this won't stay a set of buttons forever ;)

**Comment by schmittlauch** [comment]
\0/
