### ISSUE TITLE
YouTube search is broken

### ISSUE THREAD

**Issue by sehHeiden** [gpodder/gpodder-sailfish#39]
For several months I am not able to get the content from my added YouTube channels and not able to find additional channels .
For a week a so I also can not access GPodder.net and can not add Podcasts from them.
(There fore I tried to add via Soundcloud my very first time and from then I only got the Title of the cast but not the episodes.

**Comment by thp** [comment]
YouTube should be fixed with the latest version (4.6.0), but you need to add an API key to the settings page. For gpodder.net, that's a known issue (cc @stefankoegl). For Soundcloud, the channel must actually provide the download option for files to be shown in gPodder.

**Comment by thp** [comment]
Vimeo was indeed broken, and has been fixed in Git here: https://github.com/gpodder/gpodder-core/commit/5b114f20ba7fefa0443fb3b950385ca876516189 -- this fix will be included in the next release.

**Comment by thp** [comment]
I have just verified that Soundcloud still works, try the "gu-mix on Soundcloud" channel that's available in "Discover new podcasts" in the "Getting started" list.

**Comment by Meresmata** [comment]
With some work I got the api key and the added Channels were refreshed. But I could not add new YouTube channels. Could you add a help for using the Api with GPodder? Isn't it to much and to hard work for the everyday user?

Thanks.

Thanks.

**Comment by Meresmata** [comment]
Ok, I just figured out the problem more clearly. I could add YouTube Channel via their Url, but not via the YouTube search section of the app. Finding and downloading clips works.

**Comment by stefankoegl** [comment]
What exactly is the problem related to gpodder.net?

**Comment by thp** [comment]
Turning this bug into a "youtube search is broken" issue, we'll handle that here. gpodder.net issue is a known issue, and needs implementation on the client side (gpodder.net search is/was a temporary problem on the server side that since got fixed I think).

**Comment by lkraav** [comment]
I guess the easiest way to get the API key on the phone is to e-mail it to the phone right?

I'm assuming right now I typed it correctly, but search still does not show results on 4.6.0. Isn't there supposed to be some kind of an error message if the key is not valid or is empty?

**Comment by Keeper-of-the-Keys** [comment]
Closing this issue, if it is still relevant a new one should be created,
