### ISSUE TITLE
chapters: Make the time stamps clickable

### ISSUE THREAD

**Issue by cy8aer** [gpodder/gpodder-sailfish#41]
e. g. http://freakshow.fm has chapter marks. It would be nice to directly move to the positions.

**Comment by cy8aer** [comment]
ouch, go to now playing  pulley-menu->Chapters.

**Comment by citronalco** [comment]
Wow, read your comment 5 years later, having the same issue.

Without you probably I never found out how to select chapters in gPodder.
Confusingly the first few chapters are also listed in the file  information page (the one after "now playing), but no button works there.

**Comment by cy8aer** [comment]
But selecting chapters works in the newest version now.

**Comment by cy8aer** [comment]
In chapter view or long press post -> hamburger menu

**Comment by cy8aer** [comment]
oups, thought it is my own app not gpodder. Bluepill does... ahem...

**Comment by Keeper-of-the-Keys** [comment]
hehehe np. we're all a community here,  guess I'll need to add a chaptered podcast one of these days and test this.
