### ISSUE TITLE
Add support for MPRIS DBUS interface

### ISSUE THREAD

**Issue by jgibbon** [gpodder/gpodder-sailfish#43]
I'd really love gpodder on SailfishOS to register itself as a MPRIS player
- Would enable Remote Control from Lock Screen
- Would enable Remote Control from Apps (my personal use case would be "resume playing on bluetooth reconnect" using my script at https://openrepos.net/content/velox/bleh )

Would it be possible to somehow include http://wiki.gpodder.org/wiki/Extensions/MprisListener?
If not: "import org.nemomobile.mpris 1.0" isn't accepted by harbour-tools for the jolla store, so I don't know if (or how, for that matter) https://github.com/nemomobile/qtmpris has to be included locally.

What do you think?

[Edit: I have since discovered there's a Plugin for desktop gpodder. This Issue has been updated accordingly.]

**Comment by Keeper-of-the-Keys** [comment]
Striclty speaking this bug can be closed since MPRIS support is in source, however no RPM was ever released to the store, we need to figure out how to get that going.

**Comment by Keeper-of-the-Keys** [comment]
@jgibbon We are working on making a release, however the Jolla store release will not include MPRIS for now since that is still banned there, openrepos I believe may be a different story.
(Also we are still waiting for ownership transfer so that we can upload new versions)

**Comment by Keeper-of-the-Keys** [comment]
This will only be available through OpenRepos for now, hope to get setup there later this week.
