### ISSUE TITLE
Subscribe to gpodder:// urls

### ISSUE THREAD

**Issue by florianjacob** [gpodder/gpodder-sailfish#44]
Some podcasts, i.e. using the [podlove subscribe button](https://github.com/podlove/podlove-subscribe-button) use `gpodder://<podcast url>` to activate subscriptions.
I'm currently investigating what would need to be done to support that. The way forward seems to be:
- package the gpo command line tool with the rpm
- change the .desktop file to register for the url and execute `gpo subscribe <url>`

**Comment by florianjacob** [comment]
Sorry for duplicating #26. >.<

**Comment by bionade24** [comment]
Same as #26, can be closed.
