### ISSUE TITLE
How to get started fixing bugs?

### ISSUE THREAD

**Issue by jeena** [gpodder/gpodder-sailfish#46]
Hi,

I would really like to work on this app, for example to add OPML import which I feel I would able to do. My problem is that after I cloned it and updated the submodules I have no idea how to compile/start the app on my desktop and there seems not to be any documentation at all in the README or the Wiki or the page this repo links to in the short description.

Could someone help me along the way? I see some indication that I would be able to start it with qmlscene but I have no idea how.

**Comment by thp** [comment]
For the normal QML UI:

1. Clone `gpodder-core` (e.g. into `~/src/gpodder-core/`)
2. Clone `gpodder-ui-qml` (e.g. into `~/src/gpodder-ui-qml/`)
3. Install python3, qt5 and pyotherside
4. Install podcastparser using `pip3 install --user podcastparser`
5. Assuming you have cloned `gpodder-core` and `gpodder-ui-qml` next to each other, use `ln -s ../gpodder-core/src/gpodder .` inside `gpodder-ui-qml`
6. Start the UI by `qmlscene touch/gpodder.qml`

As for the Sailfish UI, you would have to build the RPM package or somehow install Sailfish Silica on your Desktop or in an Emulator of some sort. In any case, you would have to implement the corresponding features into `gpodder-core` and `gpodder-ui-qml` first, anyway and then use it from the Sailfish UI.

**Comment by jeena** [comment]
Oh wow, thanks! This works really nice, you should put that somewhere accessible where people who are interested in contributing would find that information :)

**Comment by jeena** [comment]
Ok, I was able to implement the functionality in the Desktop an Touch UI see https://github.com/gpodder/gpodder-ui-qml/pull/4 and now I am trying to implement it in the Sailfish UI too and I think my code is OK (https://github.com/jeena/gpodder-sailfish/commit/c088f63543450c00762f1f762f135a471a60d7f8) but I have the problem that I don't know how to package the thing with help of the rpm/.spec file to install my new version on my phone to test it before I can send a pull request. Do you have some tips on how to get that working?

I don't want just to replace the files, even though I guess this might work, I want some kind of a propper RPM which I can install and remove from my phone without tracking everything manually. Any tips?

**Comment by thp** [comment]
For developing/testing on Sailfish OS, assuming you have set up USB networking (also works via WIFI, just change the IPs below):

 1. `git clone --recursive https://github.com/gpodder/gpodder-sailfish.git`
 2. `cd gpodder-sailfish`
 3. `sh dev_symlinks.sh`
 4. You might want to checkout your changed version(s) of the submodules
 5. `rsync -avP . nemo@192.168.2.15:gpodder-sailfish/`
 6. `ssh nemo@192.168.2.15`
 7. `cd gpodder-sailfish`
 8. `qmlscene qml/harbour-org.gpodder.sailfish.qml`

Note that you might need to install `qmlscene` from the repositories manually (don't know the package name, sorry) and that you might need to pass the full path to the qmlscene binary (`rpm -ql <packagename>` gives a clue where it is).

**Comment by feodoran** [comment]
How do I build a new RPM? I tried `mb2 -t SailfishOS-armv7hl build` on the mersdk but ran into an error:

```cp: cannot overwrite non-directory `/home/deploy/installroot//usr/share/harbour-org.gpodder.sailfish/qml/common' with directory `gpodder-ui-qml/common'```

**Comment by thp** [comment]
I don't have an environment handy for testing here, but this should still work; did you use `--recursive` when using `git clone` (as written above) and/or have you initialized+updated the git submodules (`git submodule init` / `git submodule update`)?

**Comment by feodoran** [comment]
Yes, I followed all steps above. I just tried `git submodule init / git submodule update`, but same result. Executing with `qmlscene` on a Sailfish device works just fine.

**Comment by thp** [comment]
Have you tried removing the symlinks that were created as part of `dev_symlinks.sh`?

**Comment by feodoran** [comment]
Removing the symlinks worked. Thank you!

**Comment by Keeper-of-the-Keys** [comment]
I'm closing this issue since this is now well documented in the README.
Thanks everyone!
