### ISSUE TITLE
Further developed?

### ISSUE THREAD

**Issue by mase76** [gpodder/gpodder-sailfish#48]
Hi!
Is the Sailfish OS client further developed?

**Comment by thp** [comment]
I'm not actively working on it. It's an open source project, feel free to contribute.

**Comment by sjn** [comment]
Would it be possible to get a updated rpm at least? I see updates to podcastparser, and am wondering if that would help fix things... gPodder 4.6.0 is having trouble with http://feeds.soundcloud.com/users/soundcloud:users:59753170/sounds.rss feed.

**Comment by schmittlauch** [comment]
I'm planning to take a look into this project, but this may take a while as I'm still new to SailfishOS development.

**Comment by thp** [comment]
Closing this issue, since the original question was answered. @schmittlauch looking forward to your contributions! @sjn feel free to create a new issue; I don't have a Sailfish SDK set up currently, will have to check if the normal plain-RPM-build still works.
