### ISSUE TITLE
Show error messages for invalid certificates in UI

### ISSUE THREAD

**Issue by schmittlauch** [gpodder/gpodder-sailfish#49]
I encountered a SSL certificate verification failure when trying to download an episode. This currently (gpodder 4.6) just fails silently from an end-users perspective as the error message (kind of, it's a stacktrace) is printed to stdout, see gpodder/gpodder-core#21 This isn't really user-friendly.

I think there are at least 2 things to be done:

- [ ] catch the `ssl.SSLError` exception
- [ ] display an understandable error message

**Comment by Keeper-of-the-Keys** [comment]
I believe that 4.17.0 resolves this roughly and we'll hopefully refine it a bit.
