### ISSUE TITLE
Lucky & Fried multiple entries

### ISSUE THREAD

**Issue by cy8aer** [gpodder/gpodder-sailfish#50]
https://feeds.soundcloud.com/users/soundcloud:users:72707309/sounds.rss generates multiple entries for episode 16. RSS itself looks good.

**Comment by sfbg** [comment]
Not the case anymore:
![image](https://user-images.githubusercontent.com/24361624/62839181-bcc24a80-bc86-11e9-9c2f-4a828842fbf0.png)

Can be closed.
