### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by Meresmata** [gpodder/gpodder-sailfish#52]
Hi,

 I'd like to ask for to get more easily to the filter:"Downloaded". And also When someone is in the filter: "Fresh" to mark the episodes as old.

Thanks a lot!

**Comment by sfbg** [comment]
Also, to remember which filter was last selected, when going back to the Filters view.

**Comment by sfbg** [comment]
This one can be closed.
Remembering the filter choice is still referenced here gpodder/gpodder-sailfish#37
