### ISSUE TITLE
Syncing between different devices/plattformes

### ISSUE THREAD

**Issue by sehHeiden** [gpodder/gpodder-sailfish#54]
Hallo,

 I would kindly ask, which foulder have omto be synced to do the following:

synchronization between two different gpodder apps like one on the sailfish phone and one on the tablet or similiar. Synced shall be the list of podcast all downloaded casts and the position of the tracks.

How can tis be archived?

**Comment by peperjohnny** [comment]
As far as I know, if you copy /home/nemo/.local/share/harbour-org.gpodder.sailfish/ you should be all set. At least it worked for me, going from the Jolla C to the Xperia X. However I did this only one time, so take it with a grain of salt.

**Comment by thp** [comment]
These folders are used:

- `/home/nemo/.local/share/harbour-org.gpodder.sailfish/` -- Database + downloads
- `/home/nemo/.config/harbour-org.gpodder.sailfish/` -- Settings

There is also gpodder.net that can sync the status, but this is not implemented for gPodder 4 yet.

**Comment by Keeper-of-the-Keys** [comment]
These days there is also export OPML if you don't care about the downloaded data and registration of what you listened to and where you want to resume.

The downloads can be moved to your SD card as of the latest version but the database and settings are all still at the paths mentioned previously (`nemo` is now `defaultuser` though).

Closing, thanks everyone!
