### ISSUE TITLE
Mark video episodes differently in list

### ISSUE THREAD

**Issue by schmittlauch** [gpodder/gpodder-sailfish#57]
It might be quite useful to see already in the episodes list whether a certain episode is a video or audio file.
For that I suggest adding a video icon to the list entries of video episodes, adding an audio icon to audio episodes ma be done but isn't required IMHO.

This information should already be displayed before an episode is downloaded and may clash with the current icon indicating a downloaded episode.

**Comment by Keeper-of-the-Keys** [comment]
Hi I added this functionality, to implement this you need the last commit from pull request 62 and pull request 6 from the gpodder-ui-qml project.

It is not clear to me how alive maintenance here is, my previous pull request done over a year ago have yet to be commented on.

**Comment by Keeper-of-the-Keys** [comment]
https://github.com/gpodder/gpodder-sailfish/pull/62
https://github.com/gpodder/gpodder-ui-qml/pull/6

**Comment by Keeper-of-the-Keys** [comment]
@schmittlauch We hope to push a release to harbour/openrepos in the near future.

**Comment by schmittlauch** [comment]
@Keeper-of-the-Keys Great to see development starting again. I always wanted to help out myself, but unfortunately never found the time.

**Comment by schmittlauch** [comment]
@Keeper-of-the-Keys @elelay have you reached out to @thp or Jolla whether it is possible to migrate the Store app to another account, so that you can take over maintenance?

**Comment by Keeper-of-the-Keys** [comment]
Yes, we're going to send an e-mail to jolla developer relations today.

**Comment by Keeper-of-the-Keys** [comment]
Should show up in Jolla harbour and OpenRepos soon :)
