### ISSUE TITLE
non-ASCII characters in shownotes missing

### ISSUE THREAD

**Issue by schmittlauch** [gpodder/gpodder-sailfish#58]
Non-ASCII characters like umlauts are just not displayed in the shownotes of podcast episodes.

gPodder version: 4.6.0

This is probably a regression from the quick-and-dirty implementation of #16.

**Comment by sfbg** [comment]
I actually do not have this problem (using SFOS in Bulgarian though)

**Comment by Keeper-of-the-Keys** [comment]
Hey I'm cleaning up a bit of the older issues, @schmittlauch is this still a problem?

**Comment by schmittlauch** [comment]
Yes, this is still an issue. One affected example feed is https://feeds.hoaxilla.com/hoaxilla

**Comment by Keeper-of-the-Keys** [comment]
Very interesting I notice that in the title they are there but not in the text, later today I'll have a look at the database because I have a gut feeling that the data may not be stored correctly.

**Comment by Keeper-of-the-Keys** [comment]
The mystery deepens - in the db the data is stored correctly.

**Comment by Keeper-of-the-Keys** [comment]
OK found the issue - the episodes have an HTML description which is `RichText` and not `StyledText` type, will be in 4.17.
