### ISSUE TITLE
Remote control from headset

### ISSUE THREAD

**Issue by dimpflmoser** [gpodder/gpodder-sailfish#6]
When I play back an episode I would like to control playback from my headset buttons.
My current headset is a Bluetooth headset from Nokia (BH-505) and remote control works from Jolla's mediaplayer.

Especially while commuting I often interrupt/pause the playback skip to next episode or reverse to replay some period. It is cumbersome to get out the phone unlock it and open the dialog, especially when you have those buttons at the headset

**Comment by hmckellar** [comment]
I can confirm this issue with both the BH-505 headset and the Plantronics backbeat fit, and the Toyota Car stereo. 
@dimpflmoser is right the Jolla can receive these inputs in the media player app.

**Comment by Keeper-of-the-Keys** [comment]
This should work (though apparently it is highly device dependent whether it works without further steps by the user, JP1/X require further action, XA2 not according to TJC)
