### ISSUE TITLE
White screen after building with SDK 2.2

### ISSUE THREAD

**Issue by sfbg** [gpodder/gpodder-sailfish#68]
Using 3.0.3 kit and emulator (3.1.0 emulator has repo issues), after building and deploying the RPM to the emulator (and phone), the app starts as a white screen and I get the error:
```
[D] unknown:0 - QML Debugger: Waiting for connection on port 10081...
[W] unknown:24 - file:///usr/share/harbour-org.gpodder.sailfish/qml/harbour-org.gpodder.sailfish.qml:24:18: Type Main unavailable 
         initialPage: Main { id: main } 
                      ^
[W] unknown:24 - file:///usr/share/harbour-org.gpodder.sailfish/qml/Main.qml:24:1: "common": no such directory 
     import 'common' 
     ^
```

**Comment by Keeper-of-the-Keys** [comment]
By me the build actually fails because there is nothing that provides pyotherside-qml-plugin-python3-qt5 this may be a bug in the SDK or a change in package name, will need to check.
Either way if that is missing from the SDK it would do funcky stuff/

**Comment by sfbg** [comment]
@Keeper-of-the-Keys try it with 3.0.3 kit and emulator (instead of 3.1).
I had the exact same issue with 3.1. Apparently, the repos are not online yet for 3.1.

**Comment by sfbg** [comment]
OK, it was my noob mistake. I have failed to check out the submodules with:
`git submodule update --init`
so they were missing. Not it compiles and runs just fine.
