### ISSUE TITLE
HTML tags shown  in shownotes for some podcast episodes

### ISSUE THREAD

**Issue by sfbg** [gpodder/gpodder-sailfish#86]
For example:
![image](https://user-images.githubusercontent.com/24361624/62839332-13308880-bc89-11e9-8b70-5905facbc73f.png)

This is not the case for gPodder 3.10 for Desktop:
![image](https://user-images.githubusercontent.com/24361624/62839343-352a0b00-bc89-11e9-9b60-39832aaa9dd5.png)

**Comment by Keeper-of-the-Keys** [comment]
We would probably need to use some web-display class which to the best of my recollection exists in sailfish qml but I've never used it so far, also not sure how much bloat that would cause.

**Comment by dikonov** [comment]
A fix is proposed. See https://github.com/gpodder/gpodder-sailfish/pull/118

**Comment by thigg** [comment]
this could be closed
