### ISSUE TITLE
"Next" cover action

### ISSUE THREAD

**Issue by Keeper-of-the-Keys** [gpodder/gpodder-sailfish#92]
While a podcast is playing there are 2 cover actions: play/pause and a button that looks like "next".

I always assumed this goes to the next enqueued item but never really used it, recently I tried it and it turns out that it skips 30s in the current podcast currently being played.

I propose that:
- It should skip to the next enqueued podcast when pressed
- It should only show when other podcasts are enqueued

Your opinions on the subject are very appreciated :)

**Comment by carmenfdezb** [comment]
Hi @Keeper-of-the-Keys! For my own personal use, it is more useful skips 30s in podcast than skip to next podcast, but I understand that other users can think different way. Maybe, the best solution would be to add an option in settings to change this action in cover.

On the other hand, I think 'skip 30s' icon is not the most appropriate and should be different to 'skip next' icon

**Comment by sfbg** [comment]
I am with @carmenfdezb on this one. Mostly for skipping through ads.
Unfortunately, there is no "fast forward" icon in the Cover action category...

**Comment by Keeper-of-the-Keys** [comment]
OK I guess trying to find a FF icon is the better solution then (actually we also need that for the skip/back 1 minute in the player).
